- id: vscode-jit
  name: VSCode Jit
  description: Checks if there are new security issues that Jit IDE Extension found
  entry: vscode
  language: python
- id: gitleaks
  name: Run GitLeaks
  description: Detect secrets on the current commit
  entry: gitleaks
  language: python
